---
# defaults file for common
common_packages_redhat:
  - vim 
  - "Development Tools"
  - net-tools
  - nmap
  - tcpdump
  - wget
  - screen
  - p7zip-full

common_packages_debian:
  - vim 
  - build-essential
  - net-tools
  - nmap
  - tcpdump
  - wget
  - screen
  - p7zip-full


...
